
all:
	@echo "'make install' to install fa_schema_tools programs"

install:
	cd fa_pg_keycheck; make install
	cd fa_pg_log_groper; make install
	cd fa_pg_schema_to_tcl; make install
	cd fa_pg_schema_compare; make install
